### ISSUE TITLE
libgconf-2.so.4 error under Ubuntu 19.04

### ISSUE THREAD

**Issue by mjog** [pine64dev/etcher#11]
- Downloads/pine64-installer-2.0.0-beta.3-linux-x64.AppImage
- Ubuntu 19.04 64bit

```
mjog@blanchefort:~$ ./Downloads/pine64-installer-2.0.0-beta.3-linux-x64.AppImage 
Probably not running ./bin//pine64-installer.wrapper from within an AppImage.
Hence falling back to using .DirIcon
/tmp/.mount_22YNlE/usr/bin/pine64-installer: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by mjog** [comment]
On installing `libgconf-2-4` manually, the error above goes away, but it's pretty bad that it depends on a library that was deprecated a decade ago.

Now I get the following:

```
Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Object.exports.execFile (child_process.js:155:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:224:18)
    at Object.exports.run (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/drivelist/lib/scripts.js:85:16)
    at exports.list (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/drivelist/lib/drivelist.js:56:11)
    at createNodeObservable (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.async.js:316:6)
    at /tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.async.js:357:12
    at Rx.Observable.timer.flatMap (/tmp/.mount_twuppn/usr/bin/resources/app.asar/lib/gui/modules/drive-scanner.js:41:60)
    at tryCatcher (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:1762:31)
    at AutoDetachObserver.tryCatcher (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:1762:31)
    at /tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.time.js:116:18
    at invokeRecDate (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:993:7)
    at schedule (/tmp/.mount_twuppn/usr/bin/resources/app.asar/node_modules/rx/dist/rx.js:1312:53)
```

Wasn't AppImage supposed to fix these issues? Maybe try distributing the app via Flatpak, it's much more robust.
