### ISSUE TITLE
v2.0.0-beta.3 ( Latest release) Does not run on Fedora 33

### ISSUE THREAD

**Issue by aut0maticjack** [pine64dev/etcher#17]
- **Etcher version:** v2.0.0-beta.3
- **Operating system and architecture:**  Fedora 33 -amd64
- **Do you see any meaningful error information on DevTools?** (not running OSX)
Based on this i am going to guess you need to update your dependencies.
error is as follows:

[notroot@redacted pinephone]$ ./pine64-installer-2.0.0-beta.3-linux-x64.AppImage 
/home/notroot/.cache/thumbnails/normal/0acc4b91ec8e4c2ea18058766a12f6c2.png is missing. Probably not running ./bin//pine64-installer.wrapper from within an AppImage.
Hence falling back to using .DirIcon

(pine64-installer:84118): Pango-ERROR **: 20:45:17.017: Harfbuzz version too old (1.2.7)

Trace/breakpoint trap (core dumped)

____________________________________________________________________________________
Got essentially nothing from gdb, but here you go...
____________________________________________________________________________________
Reading symbols from pine64-installer...
(No debugging symbols found in pine64-installer)
(gdb) run
Starting program: /home/notroot/pinephone/debug/usr/bin/pine64-installer 
[New LWP 85504]
[Detaching after fork from child process 85505]
[New LWP 85507]
[New LWP 85508]

(pine64-installer:85500): Pango-ERROR **: 20:59:52.788: Harfbuzz version too old (1.2.7)

Thread 1 "pine64-installe" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff5b3e93b in ?? ()
(gdb) bt
#0  0x00007ffff5b3e93b in ?? ()
#1  0x000001c75596c4d0 in ?? ()
#2  0x0000000000000006 in ?? ()
#3  0x00007fffffffb6b0 in ?? ()
#4  0x0000000000000004 in ?? ()
#5  0x0000000000000000 in ?? ()

**Comment by Pinjontall94** [comment]
Same problem here...
